### PR TITLE
Bump protocol-redis version number

### PR DESCRIPTION
**Pull request by sailor**
Could be cool to release the latest improvements of the protocol-redis library in v0.4.2.

### CODE REVIEW

**Comment by ioquatix** [comment]
Is this necessary? Can’t you just bundle update?

**Comment by sailor** [comment]
That's what i tried at first place but it doesn't pull the latest modifications of the protocol-redis gem.

So i tried to force the version of this gem in my gemspec 

```ruby 
  spec.add_dependency 'protocol-redis', '~> 0.3.1'
  spec.add_dependency 'async-redis', '~> 0.4'
```

But i got the following errors:

```Bundler could not find compatible versions for gem "protocol-redis":
  In Gemfile:
    quiq was resolved to 0.1.0, which depends on
      async-redis (~> 0.4) was resolved to 0.4.1, which depends on
        protocol-redis (~> 0.2.0)

    quiq was resolved to 0.1.0, which depends on
      protocol-redis (~> 0.3.1)
```

**Comment by ioquatix** [comment]
I see, let me take a look, it's trying to use `~> 0.2.0` for some reason.

**Comment by ioquatix** [comment]
Okay, I didn't release the latest master yet. I will do it now. It should solve this issue.

**Comment by sailor** [comment]
Thank you very much :-)

**Comment by ioquatix** [comment]
It was fixed in v0.4.2 can you please try it and report back.

**Comment by sailor** [comment]
It works, thank's!

**Pull request closed without merging**
